spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true


  datasource:
        name: dataSource
        url: jdbc:mysql://localhost:3306/mailingsystem?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: welcome

#      "0 0 * * * *" = the top of every hour of every day.
#      "*/10 * * * * *" = every ten seconds.
#      "0 0 8-10 * * *" = 8, 9 and 10 o'clock of every day.
#     "0 0/30 8-10 * * *" = 8:00, 8:30, 9:00, 9:30 and 10 o'clock every day.
#     "0 0 9-17 * * MON-FRI" = on the hour nine-to-five weekdays
#     "0 0 0 25 12 ?" = every Christmas Day at midnight
  #cronexpression : "*/5 * * * * *"
  cronexpression : "0 1 0 ? * 6"